[package]
name = "rust-totp"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_totp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.3"
totp-rs = {version = "5.7.1", features = ["gen_secret", "otpauth", "qr", "serde", "serde_support", "url", "urlencoding", "zeroize"]}

