[build-system]
requires = ["maturin>=1.13,<2.0"]
build-backend = "maturin"

[project]
name = "rust-totp"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[project.optional-dependencies]
tests = [
    "pytest",
]
url = [
    "yarl"
]
[tool.maturin]
python-source = "python"


[project.urls]
    homepage = "https://github.com/Vizonex/pyrust-totp"
    repository = "https://github.com/Vizonex/pyrust-totp.git"
